spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_network
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOSTNAME}
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp
  application:
    security:
      jwt:
        secret-key: 8be67e57a03db3508f223121c50a16a7e9e6fe07ae127d830d827c3160d61d43
        expiration: 86400000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
    cors:
      origins: http://localhost:4200,http://localhost:8080,http://87.120.126.42:8088,http://87.120.126.42:8080
    file:
      upload:
        photos-output-path: ./uploads
server:
  port: 8088