name: BSN Frontend Pipeline

on:
  push:
    branches:
      - ci-cd
    # Triggers pipeline backend when changes are performed in the specific paths
    paths:
      - book-network-ui/**
      - docker/frontend/**
      - '../../docker-compose.yml'
      - .github/workflows/*-frontend.yml

jobs:
  build-image:
    name: Build Frontend Docker Image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract Project version
        id: extract_version
        run: | 
          cd book-network-ui
          echo "VERSION=$(jq -r '.version' package.json)" >>$GITHUB_OUTPUT

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push To Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: book-network-ui
          file: docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:latest
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}

  deploy:
    name: Deploy Frontend
    runs-on: self-hosted
    needs: [build-image]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Copy Docker-Compose File To Target Directory
        run: |
          mkdir -p ~/actions-runner/ci-cd
          cp docker-compose.yml ~/actions-runner/ci-cd/

      - name: Deploy containers
        run: |
          cd ~/actions-runner/ci-cd
          docker compose pull -q
          docker compose up -d

      - name: Set ENV Variables And Deploy
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF 
          cd ci-cd
          docker compose -f docker-compose.yml pull -q
          docker compose -f docker-compose.yml up -d
          EOF
          

